name: CI

on:
  pull_request:
  merge_group:
  push:

jobs:
  validate:
    uses: ./.github/workflows/validate_ci.yaml
    with:
      python-version: "3.12"
      os: "ubuntu:latest"

  test:
    name: "test (${{ matrix.python-version }})"
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.11", "3.12" ]
    uses: ./.github/workflows/test_ci.yaml
    with:
      python-version: ${{ matrix.python-version }}

  upload-test-coverage:
    needs: test
    uses: ./.github/workflows/upload_coverage.yaml
