name: Install

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  setup:
    runs-on: ${{inputs.os}}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: |
          poetry install

      - name: Cache Poetry
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ inputs.os }}-poetry-${{ hashFiles('poetry.lock') }}
