name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      do-coverage:
        required: true
        type: boolean
        default: false
      os:
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  test:
    runs-on: ${{inputs.os}}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Setup poetry
        run: pipx install poetry

      - name: Restore Cached Poetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ inputs.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Test with pytest
        run: |
          poetry use $ {{ inputs.python-version }}
          make test

      - name: Rename coverage file
        if: inputs.do-coverage
        run: mv .coverage .coverage.${{ inputs.python-version }}

      - name: Upload artifact
        if: inputs.do-coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .coverage.${{ inputs.python-version }}