name: Coverage

on:
  workflow_call:

jobs:
  upload-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage-data

      - name: Combine coverage files
        run: |
          python -Im pip install coverage covdefaults
          python -Im coverage xml -i

      - name: Upload report to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
