name: Validate

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: "ubuntu-latest"
      python-version:
        required: false
        type: string
        default: "3.12"

jobs:
  validate:
    runs-on: ${{inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set up Poetry
        run: pip install poetry

      - name: Restore Cache Venv
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ inputs.os }}-poetry-${{inputs.python-version}}-${{ hashFiles('poetry.lock') }}

      - name: Run Mypy
        run: |
          poetry env use ${{ inputs.python-version }}
          make analysis 

      - name: Run Ruff
        run: |
          poetry env use ${{ inputs.python-version }}
          make lint